var PRODUCTS = [
  {
    id: "ai_bundle",
    title: "AI Engineer Bundle",
    price: 499, origPrice: 1999,
    folderEnv: "GDRIVE_FOLDER_AI",
    type: "bundle", badge: "premium", badgeLabel: "Premium",
    stars: 5, reviewCount: 412,
    image: "/images/100-Natural-Language-Processing-918x1024.png",
    cat: "bundles",
    desc: "150+ Machine Learning Resources, Deep Learning Projects, and NLP Toolkit.",
    longDesc: "Complete AI development bundle containing 150+ ML projects, Deep Learning resources, NLP toolkits, and premium prompt engineering guides. Get full access to high-quality code and practical AI guides.",
    features: [
      "? 150+ Machine Learning Resources & Practical Materials",
      "? Deep Learning Project Collection",
      "? Natural Language Processing Toolkit",
      "? AI Prompt Engineering & ChatGPT Prompt Pack",
      "? Company-Level AI Project References",
      "? Lifetime Community Support"
    ],
    expandedFeatures: [
      "Machine Learning Learning Collection",
      "Deep Learning Projects",
      "NLP Resources & Datasets",
      "AI/ChatGPT Prompt Collection",
      "Coding Notes & AI Reference Materials",
      "Python Roadmap for AI Developers",
      "Productivity PDFs for Developers",
      "Interview Preparation PDFs",
      "Free DSA Resources",
      "Additional AI Learning Materials",
      "Guide to Running AI Projects",
      "Reel-Based Project Demonstrations"
    ]
  },
  {
    id: "python_bundle",
    title: "Python Developer Bundle",
    price: 499, origPrice: 1499,
    folderEnv: "GDRIVE_FOLDER_PYTHON",
    type: "bundle", badge: "hot", badgeLabel: "Hot Deal",
    stars: 5, reviewCount: 387,
    image: null,
    cat: "bundles",
    desc: "200+ Python Project Source Codes, Django Full Stack Projects, and more.",
    longDesc: "The ultimate Python resource pack. Everything from basic scripts to advanced Django architectures and ML Python implementations.",
    features: [
      "? 200+ Python Project Source Codes",
      "? Django Full Stack Project Collection",
      "? Python Games & Automation Projects",
      "? ML-Based Python Implementations",
      "? Real-World Company-Level Projects",
      "? Lifetime Community Support"
    ],
    expandedFeatures: [
      "200+ Python Projects",
      "Django Projects",
      "Games Built Using Python",
      "Machine Learning Python Implementations",
      "Company-Level Project References",
      "Python Developer Roadmap",
      "Coding Books & Notes",
      "Python Interview Questions PDF",
      "Productivity & Developer Tools PDFs",
      "VS Code Productivity Shortcuts",
      "ChatGPT Prompt Pack for Developers",
      "Free DSA Resources",
      "Additional Python Learning Materials",
      "Guide to Running Python Projects",
      "Reel Video Project Demonstrations"
    ]
  },
  {
    id: "web_bundle",
    title: "Full Stack Web Bundle",
    price: 399, origPrice: 1299,
    folderEnv: "GDRIVE_FOLDER_WEB",
    type: "bundle", badge: "premium", badgeLabel: "Premium",
    stars: 5, reviewCount: 521,
    image: "/images/react-915x1024.png",
    cat: "bundles",
    desc: "Comprehensive web development toolkit including HTML/CSS/JS, React, and PHP.",
    longDesc: "Equip yourself with the best UI templates, backend projects in PHP, and extensive modern React frontend codebases.",
    features: [
      "? 150+ HTML CSS JavaScript Projects",
      "? React Frontend Project Collection",
      "? PHP Backend Development Projects",
      "? Modern UI/Frontend Templates",
      "? Real-World Full Stack Practice Resources",
      "? Lifetime Community Support"
    ],
    expandedFeatures: [
      "HTML/CSS/JavaScript Projects",
      "React Projects",
      "PHP Projects",
      "Frontend UI Components & Templates",
      "Reel Video Frontend Demonstrations",
      "Android Development Project References",
      "Developer Productivity PDFs",
      "Coding Notes & Reference Materials",
      "VS Code Keyboard Shortcut Guide",
      "ChatGPT Prompts for Developers",
      "Interview Preparation PDFs",
      "Free DSA Resources",
      "Guide to Running Web Projects",
      "Additional Frontend & Backend Materials"
    ]
  },
  {
    id: "programming_bundle",
    title: "Programming Master Bundle",
    price: 449, origPrice: 1599,
    folderEnv: "GDRIVE_FOLDER_PROGRAMMING",
    type: "bundle", badge: "new", badgeLabel: "New",
    stars: 4, reviewCount: 201,
    image: "/images/100-Programming-Tools-927x1024.jpg",
    cat: "bundles",
    desc: "Core programming projects spanning Java, C/C++, C#, and extensive DSA notes.",
    longDesc: "From Java and C# enterprise codebases to fundamental C++ implementations, everything a core programmer needs.",
    features: [
      "? Java Project Collection",
      "? C & C++ Programming Source Codes",
      "? C# Development Projects",
      "? DSA & Core Programming Resources",
      "? Programming Roadmaps & Notes",
      "? Interview & Placement Preparation Resources"
    ],
    expandedFeatures: [
      "Java Projects",
      "C/C++ Project Source Codes",
      "C# Sharp Projects",
      "Programming Roadmaps",
      "Coding Books & Notes",
      "Free Programming Courses",
      "Games & Mini Programming Projects",
      "Interview Preparation PDFs",
      "Productivity & Developer Tools PDFs",
      "VS Code Keyboard Shortcuts",
      "ChatGPT Prompts for Programmers",
      "Free DSA Resources",
      "Additional Programming Materials",
      "Guide to Getting Started with Programming",
      "Reel Video Project Demonstrations"
    ]
  },
  {
    id: "career_bundle",
    title: "Career Accelerator Bundle",
    price: 299, origPrice: 999,
    folderEnv: "GDRIVE_FOLDER_CAREER",
    type: "bundle", badge: "", badgeLabel: "",
    stars: 5, reviewCount: 310,
    image: "/images/100-Editable-Resume-Templates-922x1024.jpg",
    cat: "career",
    desc: "Boost your career with premium resumes, interview kits, and productivity tools.",
    longDesc: "Land your next role significantly faster. The Career Bundle includes ATS-friendly resume templates, extensive interview preparation guides, and developer productivity roadmaps.",
    features: [
      "? Professional Resume Template Collection",
      "? Coding Books & Developer Notes",
      "? Productivity Toolkit for Programmers",
      "? Placement & Interview Preparation Resources",
      "? Career Growth Guides & Learning Resources",
      "? Lifetime Community Support"
    ],
    expandedFeatures: [
      "Editable Resume Templates",
      "Coding Books & Reference Notes",
      "Company-Level Project References",
      "Interview Preparation PDFs",
      "Developer Productivity Tools PDF",
      "VS Code Productivity Shortcuts",
      "ChatGPT Prompt Pack for Developers",
      "Free DSA Resources",
      "Programming Starter Guides",
      "Free Learning Resources & Courses",
      "Lifetime Community Support Materials"
    ]
  },
  {
    id: "mega_bundle",
    title: "Ultimate Mega Bundle",
    price: 999, origPrice: 4999,
    folderEnv: "GDRIVE_FOLDER_MEGA",
    type: "bundle", badge: "exclusive", badgeLabel: "Special Offer",
    stars: 5, reviewCount: 154,
    image: "/images/Developers-Kit-1943x2048-1-972x1024.png",
    cat: "bundles",
    desc: "Get absolutely EVERYTHING on the platform in one ultimate collection.",
    longDesc: "Why choose when you can have it all? The Mega Bundle provides instant access to every single project, roadmap, PDF, and resource on the site.",
    features: [
      "? Access to All AI, Python, Web & Programming Projects",
      "? Complete Collection of Coding Notes & Interview Prep",
      "? All Resume Templates & Productivity PDF Toolkit",
      "? All Bonus Materials and Roadmaps",
      "? Lifetime Access to All Current & Future Resources",
      "? Priority 24/7 Community Support"
    ],
    expandedFeatures: [
      "Everything in AI Engineer Bundle",
      "Everything in Python Developer Bundle",
      "Everything in Full Stack Web Bundle",
      "Everything in Programming Master Bundle",
      "Everything in Career Accelerator Bundle",
      "All Future Updates Included",
      "Priority Developer Access"
    ]
  }
];
