var PRODUCTS = [
  {
    id: "ai_bundle",
    title: "AI Engineer Bundle",
    price: 2,
    origPrice: 1999,
    folderEnv: "GDRIVE_FOLDER_AI",
    type: "bundle",
    badge: "premium",
    badgeLabel: "AI + ML",
    stars: 5,
    reviewCount: 412,
    image: "/images/150-Machine-Learnig-1-919x1024.png",
    cat: "ai",
    desc: "Machine Learning, Deep Learning, NLP, AI prompts, and project references in one focused bundle.",
    longDesc: "A focused AI learning and project bundle for developers who want practical ML, Deep Learning, NLP, prompt engineering, and real project references in one place.",
    features: [
      "150+ Machine Learning resources and practical materials",
      "Deep Learning project collection",
      "Natural Language Processing toolkit",
      "AI prompt engineering and ChatGPT prompt pack",
      "Company-level AI project references",
      "Lifetime community support"
    ],
    expandedFeatures: [
      "Machine Learning learning collection",
      "Deep Learning projects",
      "NLP resources and datasets",
      "AI and ChatGPT prompt collection",
      "Coding notes and AI reference materials",
      "Python roadmap for AI developers",
      "Productivity PDFs for developers",
      "Interview preparation PDFs",
      "Free DSA resources",
      "Additional AI learning materials",
      "Guide to running AI projects",
      "Reel-based project demonstrations"
    ]
  },
  {
    id: "python_bundle",
    title: "Python Developer Bundle",
    price: 2,
    origPrice: 1499,
    folderEnv: "GDRIVE_FOLDER_PYTHON",
    type: "bundle",
    badge: "hot",
    badgeLabel: "Hot Deal",
    stars: 5,
    reviewCount: 387,
    image: "/images/300-Python-Projects-915x1024.png",
    cat: "python",
    desc: "Python projects, Django apps, automation, games, ML implementations, and developer prep resources.",
    longDesc: "The Python Developer Bundle gives you Python source codes, Django projects, games, automation ideas, ML implementations, notes, prompts, and practical project-running guides.",
    features: [
      "200+ Python project source codes",
      "Django full stack project collection",
      "Python games and automation projects",
      "ML-based Python implementations",
      "Real-world company-level projects",
      "Lifetime community support"
    ],
    expandedFeatures: [
      "200+ Python projects",
      "Django projects",
      "Games built using Python",
      "Machine Learning Python implementations",
      "Company-level project references",
      "Python developer roadmap",
      "Coding books and notes",
      "Python interview questions PDF",
      "Productivity and developer tools PDFs",
      "VS Code productivity shortcuts",
      "ChatGPT prompt pack for developers",
      "Free DSA resources",
      "Additional Python learning materials",
      "Guide to running Python projects",
      "Reel video project demonstrations"
    ]
  },
  {
    id: "web_bundle",
    title: "Full Stack Web Bundle",
    price: 2,
    origPrice: 1299,
    folderEnv: "GDRIVE_FOLDER_WEB",
    type: "bundle",
    badge: "premium",
    badgeLabel: "Full Stack",
    stars: 5,
    reviewCount: 521,
    image: "/images/150-Front-end-Projects-915x1024.png",
    cat: "web",
    desc: "Frontend projects, React, PHP backend practice, UI templates, and web development references.",
    longDesc: "A practical web development bundle with HTML, CSS, JavaScript, React, PHP, UI templates, frontend demonstrations, and supporting developer resources.",
    features: [
      "150+ HTML CSS JavaScript projects",
      "React frontend project collection",
      "PHP backend development projects",
      "Modern UI and frontend templates",
      "Real-world full stack practice resources",
      "Lifetime community support"
    ],
    expandedFeatures: [
      "HTML, CSS, and JavaScript projects",
      "React projects",
      "PHP projects",
      "Frontend UI components and templates",
      "Reel video frontend demonstrations",
      "Android development project references",
      "Developer productivity PDFs",
      "Coding notes and reference materials",
      "VS Code keyboard shortcut guide",
      "ChatGPT prompts for developers",
      "Interview preparation PDFs",
      "Free DSA resources",
      "Guide to running web projects",
      "Additional frontend and backend materials"
    ]
  },
  {
    id: "programming_bundle",
    title: "Programming Master Bundle",
    price: 2,
    origPrice: 1599,
    folderEnv: "GDRIVE_FOLDER_PROGRAMMING",
    type: "bundle",
    badge: "new",
    badgeLabel: "Core CS",
    stars: 4,
    reviewCount: 201,
    image: "/images/Java-915x1024.png",
    cat: "programming",
    desc: "Java, C, C++, C#, DSA, roadmaps, coding notes, and interview preparation material.",
    longDesc: "A core programming bundle for strengthening fundamentals with Java projects, C/C++ source codes, C# projects, DSA resources, roadmaps, notes, and placement preparation.",
    features: [
      "Java project collection",
      "C and C++ programming source codes",
      "C# development projects",
      "DSA and core programming resources",
      "Programming roadmaps and notes",
      "Interview and placement preparation resources"
    ],
    expandedFeatures: [
      "Java projects",
      "C/C++ project source codes",
      "C# Sharp projects",
      "Programming roadmaps",
      "Coding books and notes",
      "Free programming courses",
      "Games and mini programming projects",
      "Interview preparation PDFs",
      "Productivity and developer tools PDFs",
      "VS Code keyboard shortcuts",
      "ChatGPT prompts for programmers",
      "Free DSA resources",
      "Additional programming materials",
      "Guide to getting started with programming",
      "Reel video project demonstrations"
    ]
  },
  {
    id: "career_bundle",
    title: "Career Accelerator Bundle",
    price: 2,
    origPrice: 999,
    folderEnv: "GDRIVE_FOLDER_CAREER",
    type: "bundle",
    badge: "exclusive",
    badgeLabel: "Career Kit",
    stars: 5,
    reviewCount: 310,
    image: "/images/100-Editable-Resume-Templates-922x1024.jpg",
    cat: "career",
    desc: "Resume templates, interview preparation, coding notes, productivity tools, and career resources.",
    longDesc: "A career-focused bundle with resume templates, interview PDFs, notes, productivity tools, shortcuts, prompts, guides, and learning resources for developers.",
    features: [
      "Professional resume template collection",
      "Coding books and developer notes",
      "Productivity toolkit for programmers",
      "Placement and interview preparation resources",
      "Career growth guides and learning resources",
      "Lifetime community support"
    ],
    expandedFeatures: [
      "Editable resume templates",
      "Coding books and reference notes",
      "Company-level project references",
      "Interview preparation PDFs",
      "Developer productivity tools PDF",
      "VS Code productivity shortcuts",
      "ChatGPT prompt pack for developers",
      "Free DSA resources",
      "Programming starter guides",
      "Free learning resources and courses",
      "Lifetime community support materials"
    ]
  },
  {
    id: "mega_bundle",
    title: "Ultimate Mega Bundle",
    price: 2,
    origPrice: 4999,
    folderEnv: "GDRIVE_FOLDER_MEGA",
    type: "bundle",
    badge: "exclusive",
    badgeLabel: "Everything",
    stars: 5,
    reviewCount: 154,
    image: "/images/Developers-Kit-1943x2048-1-972x1024.png",
    cat: "mega",
    desc: "Every bundle on the platform: AI, Python, Web, Programming, Career, bonuses, and future updates.",
    longDesc: "The complete Code Hunters collection with every bundle, project pack, roadmap, PDF, reference material, bonus resource, and future update included.",
    features: [
      "Access to all AI, Python, Web and Programming projects",
      "Complete coding notes and interview prep collection",
      "All resume templates and productivity PDF toolkit",
      "All bonus materials and roadmaps",
      "Lifetime access to all current and future resources",
      "Priority community support"
    ],
    expandedFeatures: [
      "Everything in AI Engineer Bundle",
      "Everything in Python Developer Bundle",
      "Everything in Full Stack Web Bundle",
      "Everything in Programming Master Bundle",
      "Everything in Career Accelerator Bundle",
      "All future updates included",
      "Priority developer access"
    ]
  }
];
